### ISSUE TITLE
Small question about padding function

### ISSUE THREAD

**Issue by amorehead** [jasonkyuyim/se3_diffusion#11]
Hello again. Looking at your `pad` function when `torch=True`, first off, it looks like one will need to rename this `torch` function argument to something like `torch_inputs` to not overwrite the `torch` module import in this `utils.py` file. Another thing is, does this `torch.pad` function exist in PyTorch `master` yet?

https://github.com/jasonkyuyim/se3_diffusion/blob/420b1fe6d3da53ff17490e5b599df2acca5039e5/data/utils.py#L246

**Comment by jasonkyuyim** [comment]
Good catch! We never used the torch option so this isn't a bug anywhere but it would raise a namespace error. I've pushed a fix here https://github.com/jasonkyuyim/se3_diffusion/commit/fb350b69ca4349d7b29b19044ecc8627815dafce
