### ISSUE TITLE
Unused PyTorch modules

### ISSUE THREAD

**Issue by amorehead** [jasonkyuyim/se3_diffusion#14]
For clarification, is it true that the following PyTorch nn.Modules are indeed unused by your model?

https://github.com/jasonkyuyim/se3_diffusion/blob/fb350b69ca4349d7b29b19044ecc8627815dafce/model/ipa_pytorch.py#L300

https://github.com/jasonkyuyim/se3_diffusion/blob/fb350b69ca4349d7b29b19044ecc8627815dafce/model/ipa_pytorch.py#L483

**Comment by jasonkyuyim** [comment]
Thanks. Yes these module are unused. They can be removed if memory is an issue. I added a TODO to remove this after training a checkpoint without this unused module. https://github.com/jasonkyuyim/se3_diffusion/commit/a739080859f0abd1ea216c6907b3028a7ed3c4b3
