### ISSUE TITLE
Does `DistributedTrainSampler` also need to be updated for `cluster` support?

### ISSUE THREAD

**Issue by amorehead** [jasonkyuyim/se3_diffusion#25]
https://github.com/jasonkyuyim/se3_diffusion/blob/5be5b367bda4cc075fc9edc195188251acb846fe/experiments/train_se3_diffusion.py#L203

Hello. I was curious if the `DistributedTrainSampler` needs to be updated in response to the most recent changes to `TrainSampler` for clustering support. A related question is, does the `batch_size=256` choice in `base.yml` correspond to training with a single A100 (80GB) GPU (instead of two A100s as originally done), by chance? If so, that would explain how and why DDP is currently not being used (since `DistributedTrainSampler` appears to not support clustering yet).

**Comment by jasonkyuyim** [comment]
Hi, I don't use `DistributedTrainSampler` so I can't help much. I think just copying over the clustering code should work. (Ideally the samplers would inherit from a base sampler.) `batch_size=256` was used with 2 40gb A100s so in theory a single 80gb A100 should work.

**Comment by amorehead** [comment]
Thanks for your quick reply. I think, going forward, it may make sense to replace `DistributedTrainSampler` with Lightning Fabric's [`DistributedSamplerWrapper`](https://github.com/Lightning-AI/lightning/blob/23776b0dedf2bccdc97b21e47029db786b8bd8b1/src/lightning/fabric/utilities/distributed.py#L294). This neat class allows you to pass it an arbitrary custom `Sampler` (like `TrainSampler`), and it will handle all distributed sharding of the underlying dataset's indices (as I understand it). I'll personally be trying this out in PyTorch Lightning to see if it works as expected.
