### ISSUE TITLE
How to generate dynamic images in the demo?

### ISSUE THREAD

**Issue by wewewexiao2008** [jasonkyuyim/se3_diffusion#28]
The initial secondary structure exhibits remarkable characteristics. I'm wondering how to reproduce it with my own structure.

**Comment by jasonkyuyim** [comment]
Hi, I use https://marketplace.visualstudio.com/items?itemName=ArianJamasb.protein-viewer 

Take `x0_traj_1.pdb` from a good looking sample after running inference (I use noise scale 0.1) then open up protein-viewer on this file.

1. Click Stylized in "Quick styles".
2. Change "Set coloring" to Atom property -> Element Index.
3. Export animation where there should be a button to do the reverse trajectory.

Attached is a screenshot of what the UI looks like for me.
<img width="1166" alt="Screenshot 2023-07-22 at 12 03 52 AM" src="https://github.com/jasonkyuyim/se3_diffusion/assets/74610237/bfb216eb-5f04-4fd5-a7ef-6319581ec7b2">

**Comment by jasonkyuyim** [comment]
https://github.com/jasonkyuyim/se3_diffusion/assets/74610237/51e1099f-2004-44f8-9c2f-95c2702eea7d

**Comment by wewewexiao2008** [comment]
Thanks a lot! Another question: It has come to my attention that despite the presence of multiple models in the pdb file, the model number consistently appears as 1 instead of 50, or 500, as observed in your case. 
The RFDiffusion is employed for my model generation. Could you kindly provide information regarding the specific label that requires modification in the pdb file to facilitate successful parsing by pdbviewer?
![image](https://github.com/jasonkyuyim/se3_diffusion/assets/43698415/c287128f-d04d-49c0-98f5-0bf4ac70ff05)

**Comment by wewewexiao2008** [comment]
The annotation for MODEL 1 and MODEL 2 is missing in the PDB file. After adding them, the recognition can be performed correctly.

![image](https://github.com/jasonkyuyim/se3_diffusion/assets/43698415/97d9bb5c-8ecc-4796-a38c-eec116ddcedf)

**Comment by Mistletoe-git** [comment]
It's helpful for me!
