### ISSUE TITLE
Issue with FileNotFoundError for sample_1.fa during inference

### ISSUE THREAD

**Issue by RinGhalSun** [jasonkyuyim/se3_diffusion#30]
Hi Jason,

I'm encountering an issue while running inference using the protein_mpnn package. The problem occurs when attempting to sample sequences of length 305. Specifically, I'm receiving the following error:

`FileNotFoundError: [Errno 2] No such file or directory: './inference_outputs/23D_08M_2023Y_00h_09m_35s/length_305/sample_1/self_consistency/seqs/sample_1.fa'`

It's worth noting that the file length_305/sample_0/self_consistency/seq/sample_1.fa was successfully generated. However, the corresponding sample_1.fa file for the first sample of length_305/sample_1/self_consistency/seq/sample_1.fa fails to be generated by the protein_mpnn package.

Kind regards,

Zheng

**Comment by jasonkyuyim** [comment]
Hi, I see this issue happen from time to time. I found that re-running the script again solves the issue. Since restarting works, I was too lazy to look into what was going on haha...

**Comment by RinGhalSun** [comment]
lol, thanks a lot mate!
