### ISSUE TITLE
Small issue about warm start in training code

### ISSUE THREAD

**Issue by Immortals-33** [jasonkyuyim/se3_diffusion#34]
Hi Jason & Brian, thanks for this inspiring work! 
 
When I look through the training code, a potential issue occured:  
https://github.com/jasonkyuyim/se3_diffusion/blob/53359d71cfabc819ffaa571abd2cef736c871a5d/experiments/train_se3_diffusion.py#L97-L103  
Seems that the `ckpt_dir` is referred as a boolean value here. Was it intended to set to `ckpt_dir = conf.experiment.ckpt_dir` ? 
https://github.com/jasonkyuyim/se3_diffusion/blob/53359d71cfabc819ffaa571abd2cef736c871a5d/config/base.yaml#L99-L102  
Btw running the training code without setting the `warm_start` option is OK.

**Comment by jasonkyuyim** [comment]
Hi and thanks for the kind words. `warm_start` is the checkpoint directory of the weights we want to start training from. If `warm_start` is null then the weights are initialized from scratch.`ckpt_dir` is the directory the current experiment will saved checkpoints to. So the logic shuld be correct. I should've named the variables differently, my apologies.
