### ISSUE TITLE
Evaluating diversity of structures

### ISSUE THREAD

**Issue by Guo-Stone** [jasonkyuyim/se3_diffusion#35]
Dear authors,
could you share your code about diversity evaluating with MaxCluster?
Thanks a lot!

**Comment by jasonkyuyim** [comment]
Do you mean the maxcluster command? We use this 
`maxcluster64bit -l <pdb_list> ./all_by_all_lite -C 2 -in -Rl ./tm_results.txt -Tm 0.5 >  ./output.txt`

Where `<pdb_list>` is a text file with one pdb path per line of the proteins to cluster.

**Comment by Guo-Stone** [comment]
Thanks a lot !
