### ISSUE TITLE
One Question about Validation (Intermittent evaluation)

### ISSUE THREAD

**Issue by cnexah** [jasonkyuyim/se3_diffusion#36]
Hi, thank you for your great work!
I have a question about the input data during validation (Intermittent evaluation):

In the following code:

https://github.com/jasonkyuyim/se3_diffusion/blob/53359d71cfabc819ffaa571abd2cef736c871a5d/data/pdb_data_loader.py#L260

In the dataloader, during validation, the input to the model is random noise, but the ground truth is obtained by sampling from data.
Is it meaningful to compute the TM-score metric?
https://github.com/jasonkyuyim/se3_diffusion/blob/53359d71cfabc819ffaa571abd2cef736c871a5d/experiments/train_se3_diffusion.py#L382

**Comment by jasonkyuyim** [comment]
Hi! The intermittent TM-score during evaluation is not meaningful for unconditional generation. We were experimenting with ensembles and forward folding performance for which TM-score was useful. You can ignore that metric depending on the task at hand.

**Comment by cnexah** [comment]
I see. Thank you for your reply!
