### ISSUE TITLE
Question on RMSD Calculation

### ISSUE THREAD

**Issue by Immortals-33** [jasonkyuyim/se3_diffusion#40]
Hi, 

Thanks again for this awesome work.
When I look through the code of calculating RMSD: https://github.com/jasonkyuyim/se3_diffusion/blob/53359d71cfabc819ffaa571abd2cef736c871a5d/analysis/metrics.py#L71-L73

It first calculates the rigid alignment of two positions, then calculates the $\mathcal{l}_2$-norm over the last axis ($x, y, z$), finally mean over all residues $N$. Suppose the two proteins to be calculated as $\vec{x}, \vec{y}$, This produces the following calculation:

$$
RMSD_{current} = \frac{1}{N} {\sum_{i=1}^N \parallel \vec{x_i} - \vec{y_i} \parallel_2}
$$

According to the standard definition of RMSD:

$$
RMSD_{standard} = \sqrt{\frac{1}{N} \sum_{i=1}^N \parallel \vec{x_i} - \vec{y_i} \parallel_2^2}
$$

So if I'm not mistaken, the standard RMSD calculation should be:
```python
def calc_aligned_rmsd(pos_1, pos_2):
    aligned_pos_1 = rigid_transform_3D(pos_1, pos_2)[0]
    return np.sqrt(np.mean(np.linalg.norm(aligned_pos_1 - pos_2, axis=-1) ** 2))
```

In practice, the former calculation might produce a value slightly smaller than the latter one. Is this expected or is a bug? If this should be reformulated I would be happy to open a PR.

Best,
Zhuoqi

**Comment by jasonkyuyim** [comment]
Hi Zhuoqi, thanks for the question. The current implementation is correct. We don't want to take the squared norm then square root. To be clear, we are computing the averaged RMSD over all residues.

**Comment by Immortals-33** [comment]
Hi Jason, thanks for your response and clarification. So if I'm not mistaken, is the current implementation calculating the Euclidean distance between each pair of residues, sum up, and average over all residues after optimal alignment (minimizing RMSD)? Seems like another way for RMSD calculation different from some other implementations like [OpenFold](https://github.com/aqlaboratory/openfold/blob/6f63267114435f94ac0604b6d89e82ef45d94484/openfold/utils/multi_chain_permutation.py#L10-L32) and [Biotite](https://github.com/biotite-dev/biotite/blob/53256ed71f2e069482f7913604e7b6a998c835ca/src/biotite/structure/compare.py#L20-L72).

**Comment by meneshail** [comment]
Hi Yim and Zhuoqi,
Actually I also share the same question. Based on my research, most RMSD implementations follow the second formula. For example, you can find this in:
- [MDAnalysis](https://docs.mdanalysis.org/1.1.1/documentation_pages/analysis/rms.html#MDAnalysis.analysis.rms.rmsd)
- [mdtraj](https://github.com/mdtraj/mdtraj/blob/b4447a1a6e8e9899bafec4d7ffb8bdce5d41aa60/mdtraj/rmsd/_rmsd.pyx#L62C1-L207C43)
- [GROMACS](https://manual.gromacs.org/2024.0/reference-manual/analysis/rmsd.html#root-mean-square-deviations-in-structure)
- [Amber](https://ambermd.org/tutorials/analysis/tutorial1/index.php#Introduction)

Additionally, I believe the rigid transformation used to align the two structures minimizes the sum of squared errors, and not necessarily the sum of absolute errors (as calculated in the current implementation)[1]:

$$
L=\sum_{i=1}^N \left\|  x_i-\left(R y_i+T\right) \right\|^2 .
$$

which further justifies using the second formula.

[1] K. S. Arun, T. S. Huang and S. D. Blostein, "Least-Squares Fitting of Two 3-D Point Sets," in IEEE Transactions on Pattern Analysis and Machine Intelligence, vol. PAMI-9, no. 5, pp. 698-700, Sept. 1987, doi: 10.1109/TPAMI.1987.4767965.

**Comment by jasonkyuyim** [comment]
Interesting... I didn't know other implementations used the second formula. $RMSD_{current}$ is more intuitive to me since it is the average RMSD across residues (after alignment). The notion of pairwise distances is muddled in $RMSD_{standard}$ so I don't like it as much. Nevertheless, both are monotonic so you can use whichever definition you wish as long as it's consistent. I think I will keep my implementation in this codebase to not mess up RMSD for folks who already copied/forked the code.

**Comment by Immortals-33** [comment]
Thanks for the replies.
