### ISSUE TITLE
Some questions about dataprocessing code for multimer 

### ISSUE THREAD

**Issue by sirius777coder** [jasonkyuyim/se3_diffusion#41]
Hi,
I really appreciate this codebase and am excited to use it for working with complex structures. However, I noticed that the data processing code currently treats each chain independently and removes the mean CA translations to centerize this chain.This approach causes the complex structure to collapse. Would it be possible to add a function to adjust for cases with more than two chains, allowing us to subtract the mean CA positions across all chains collectively?

https://github.com/jasonkyuyim/se3_diffusion/blob/53359d71cfabc819ffaa571abd2cef736c871a5d/data/process_pdb_dataset.py#L177
https://github.com/jasonkyuyim/se3_diffusion/blob/53359d71cfabc819ffaa571abd2cef736c871a5d/data/utils.py#L436-L445

**Comment by jasonkyuyim** [comment]
Hi, yes this is possible to adjust for complexes - I don't think it's difficult. I'd like to keep this repo for the single chain case. You're free to fork this repo and make your own changes.

**Comment by sirius777coder** [comment]
Thanks ! We can just to translate all the complex together.
