### ISSUE TITLE
J.1. Training details

### ISSUE THREAD

**Issue by LivC93** [jasonkyuyim/se3_diffusion#43]
Hi, tks for making this repo public and documented. 

I have a couple of questions
1. In `J.1. Training details` you outline the filtering protocol used to reach the final training set. Would it be possible to have an exact list of PDBs used for training? This will help when comparing with new models, in order to make sure the training sets are identical.
2. What do you do with structures that have missing backbone atoms (i.e. chain breaks)? I could not find any details in the paper regarding this aspect.

**Comment by jasonkyuyim** [comment]
Hi,

1. You can download preprocessed_pdb.tar.gz [here](https://zenodo.org/records/12776473?token=eyJhbGciOiJIUzUxMiJ9.eyJpZCI6Ijg2MDUzYjUzLTkzMmYtNDRhYi1iZjdlLTZlMzk0MmNjOGM3NSIsImRhdGEiOnt9LCJyYW5kb20iOiIwNjExMjEwNGJkMDJjYzRjNGRmNzNmZWJjMWU4OGU2ZSJ9.Jo_xXr6-PpOzJHUEAuSmQJK72TMTcI49SStlAVdOHoI2wi1i59FeXnogHvcNioBjGiJtJN7UAxc6Ihuf1d7_eA) then look at the `metadata.csv` which contains the PDB IDs.

2. We don't modify chain breaks in the data. The model sees chain breaks but can handle them because of positional encodings, i..e. it will know there's a chain break and place its residues accordingly.

**Comment by LivC93** [comment]
@jasonkyuyim tks for the message. I downloaded both versions of the `tar` file and there is no `metadata.csv` in either version. Let me know if I did something wrong.

Tks for explaining the second point.

**Comment by jasonkyuyim** [comment]
Sorry, the metadata.csv is here https://github.com/jasonkyuyim/multiflow/tree/main/metadata . Download this file for the PDB IDs. https://github.com/jasonkyuyim/multiflow/blob/main/metadata/pdb_metadata.csv

**Comment by LivC93** [comment]
@jasonkyuyim amazing thank you very much for your help. Just in case anybody in the future will want to reproduce what we discussed I will leave below my filtering and comments.
I followed the filtering procedure explained in the [J.1. Training details](https://arxiv.org/abs/2302.02277) section of the FrameDiff paper. According to the authors the final number of PDBs used for training should be `20312 proteins`

I used the `pdb_metadata.csv` you linked above to filter it according to the J.1 section using these filters

```
df = pd.read_csv('./pdb_metadata.csv')
df_filtered = df[(df['oligomeric_detail'].str.contains(r'\bmonomeric\b')) &
                  (df['oligomeric_count'].str.contains(r'\b1\b')) &
                  (df['num_chains'] == 1) & 
                  (df['coil_percent'] < 0.5)]
```

I ended up with `21,236 PDB ids` which is a bit more than the reported `20312 proteins`. However, it is fairly possible that the starting dataset is not exactly the same to the one used in the paper. For example I can see 
entries like: 
1. [6Z1L](https://www.rcsb.org/structure/6Z1L) that have been released on `2021-08-25`, which is after the cutoff date mentioned in the paper ` downloaded from PDB (Berman et al., 2000) on August 8, 2021`
2. [6WHH](https://www.rcsb.org/structure/removed/6WHH) that have been deprecated.


If you could confirm that the filters I used are satisfactory and reflect the ones used in the FrameDiff paper I am more than happy to consider this issue closed.

Thank you very much for your help with this matter.

**Comment by jasonkyuyim** [comment]
That's fine to me.
